#!/usr/bin/env bash
# capture-monitor-profile.sh -- snapshot the live monitor layout into a profile.
#
# Workflow: arrange the displays however you like (nwg-displays, or by hand),
# then run this. It rewrites monitor_profiles/<profile>.monitors.lua from the
# running session, keyed by EDID description so the result survives the KVM
# renumbering connectors.
#
#   capture-monitor-profile.sh [profile]            # default: kvm
#   capture-monitor-profile.sh kvm --dry-run        # print, write nothing
#   capture-monitor-profile.sh kvm --with-workspaces
#   capture-monitor-profile.sh kvm --yes            # skip the confirmation
#
# Workspace pinning is NOT snapshotted by default -- see the note under
# --with-workspaces below.
set -uo pipefail

CONFIG_DIR="${HYPR_DIR:-${XDG_CONFIG_HOME:-$HOME/.config}/hypr}"
PROFILE_DIR="${HYPR_PROFILE_DIR:-$CONFIG_DIR/monitor_profiles}"
HYPRCTL="${HYPRCTL:-hyprctl}"

PROFILE=kvm
DRY_RUN=0
ASSUME_YES=0
WITH_WORKSPACES=0

for arg in "$@"; do
  case "$arg" in
    --dry-run) DRY_RUN=1 ;;
    --yes | -y) ASSUME_YES=1 ;;
    --with-workspaces) WITH_WORKSPACES=1 ;;
    -*)
      printf 'usage: %s [profile] [--dry-run] [--yes] [--with-workspaces]\n' \
        "$(basename "$0")" >&2
      exit 2
      ;;
    *) PROFILE="$arg" ;;
  esac
done

command -v jq >/dev/null 2>&1 || { printf 'jq is required\n' >&2; exit 1; }

LIVE_JSON="$("$HYPRCTL" -j monitors 2>/dev/null)" || {
  printf 'cannot read monitors -- is Hyprland running?\n' >&2
  exit 1
}
jq -e 'type == "array" and length > 0' >/dev/null 2>&1 <<<"$LIVE_JSON" || {
  printf 'hyprctl returned no monitors; refusing to capture an empty layout\n' >&2
  exit 1
}

MONITORS_OUT="$PROFILE_DIR/$PROFILE.monitors.lua"
WORKSPACES_OUT="$PROFILE_DIR/$PROFILE.workspaces.lua"

# ── Render monitors ─────────────────────────────────────────────────────────
# Monitors without an EDID description (rare, and true of some internal panels)
# fall back to the connector name, which is stable for a built-in display.
render_monitors() {
  printf '%s\n' \
    "-- Generated by capture-monitor-profile.sh on $(date '+%Y-%m-%d %H:%M:%S')." \
    "-- Monitors are keyed by EDID description: the KVM renumbers DisplayPort" \
    "-- connectors on every switch, so connector names are not stable here." \
    "-- Re-capture with: ~/.config/hypr/scripts/capture-monitor-profile.sh $PROFILE" \
    ""

  # The internal panel is disabled in docked layouts; record that explicitly so
  # the applier can assert it rather than leaving it to chance.
  if ! jq -e '.[] | select(.name == "eDP-1")' >/dev/null 2>&1 <<<"$LIVE_JSON"; then
    printf '%s\n' \
      'hl.monitor({' \
      '    output = "eDP-1",' \
      '    disabled = true,' \
      '})' \
      ''
  fi

  jq -r 'sort_by(.x) | .[] |
    (if (.description // "") == "" then .name else "desc:" + .description end) as $key |
    "hl.monitor({\n" +
    "    output = \"" + $key + "\",\n" +
    "    mode = \"" + (.width|tostring) + "x" + (.height|tostring) + "@"
        + ((.refreshRate*100|round/100)|tostring) + "\",\n" +
    "    position = \"" + (.x|tostring) + "x" + (.y|tostring) + "\",\n" +
    "    scale = " + ((.scale*100|round/100)|tostring) + ",\n" +
    "    transform = " + (.transform|tostring) + ",\n" +
    "})\n"' <<<"$LIVE_JSON"
}

# ── Render workspace pinning ────────────────────────────────────────────────
# Only reachable via --with-workspaces. Workspaces that are not currently open
# have no live monitor to read, so they inherit the previous band and are
# reported as inferred -- review before keeping.
render_workspaces() {
  local placement inferred=()
  placement="$("$HYPRCTL" -j workspaces 2>/dev/null |
    jq -r '.[] | select(.id >= 1 and .id <= 15) | "\(.id) \(.monitor)"')"

  printf '%s\n' \
    "-- Generated by capture-monitor-profile.sh on $(date '+%Y-%m-%d %H:%M:%S')." \
    "-- Keyed by EDID description, see $PROFILE.monitors.lua." \
    ""

  local ws name key last=""
  for ws in $(seq 1 15); do
    name="$(awk -v w="$ws" '$1 == w { print $2 }' <<<"$placement")"
    if [[ -n "$name" ]]; then
      key="$(jq -r --arg n "$name" \
        'first(.[] | select(.name == $n)) |
         if (.description // "") == "" then .name else "desc:" + .description end' \
        <<<"$LIVE_JSON")"
      last="$key"
    else
      key="$last"
      inferred+=("$ws")
    fi
    [[ -n "$key" ]] || key="$(jq -r 'sort_by(.x) | .[0].name' <<<"$LIVE_JSON")"
    printf 'hl.workspace_rule({\n    workspace = "%s",\n    monitor = "%s",\n    default = %s,\n})\n\n' \
      "$ws" "$key" "$([[ "$ws" == 1 ]] && echo true || echo false)"
  done

  if ((${#inferred[@]} > 0)); then
    printf 'inferred (not currently open, inherited from the previous band): %s\n' \
      "${inferred[*]}" >&2
  fi
}

# ── Preview, confirm, write ─────────────────────────────────────────────────
tmp_monitors="$(mktemp)"
trap 'rm -f "$tmp_monitors" "${tmp_workspaces:-}"' EXIT
render_monitors >"$tmp_monitors"

command -v luac >/dev/null 2>&1 && { luac -p "$tmp_monitors" || {
  printf 'generated monitors Lua is invalid; refusing to write\n' >&2; exit 1; }; }

printf '=== %s ===\n' "$MONITORS_OUT"
if [[ -f "$MONITORS_OUT" ]]; then
  diff -u --label current --label captured "$MONITORS_OUT" "$tmp_monitors" || true
else
  cat "$tmp_monitors"
fi

if ((WITH_WORKSPACES)); then
  tmp_workspaces="$(mktemp)"
  render_workspaces >"$tmp_workspaces"
  command -v luac >/dev/null 2>&1 && { luac -p "$tmp_workspaces" || {
    printf 'generated workspaces Lua is invalid; refusing to write\n' >&2; exit 1; }; }
  printf '\n=== %s ===\n' "$WORKSPACES_OUT"
  if [[ -f "$WORKSPACES_OUT" ]]; then
    diff -u --label current --label captured "$WORKSPACES_OUT" "$tmp_workspaces" || true
  else
    cat "$tmp_workspaces"
  fi
fi

if ((DRY_RUN)); then
  printf '\ndry-run: nothing written\n'
  exit 0
fi

if ((ASSUME_YES == 0)); then
  printf '\nWrite these files? [y/N] '
  read -r reply
  [[ "$reply" == [yY]* ]] || { printf 'aborted\n'; exit 0; }
fi

for pair in "$tmp_monitors:$MONITORS_OUT" "${tmp_workspaces:-}:${WORKSPACES_OUT}"; do
  src="${pair%%:*}"; dst="${pair##*:}"
  [[ -n "$src" && -f "$src" ]] || continue
  [[ -f "$dst" ]] && cp "$dst" "$dst.bak"
  cp "$src" "$dst"
  printf 'wrote %s\n' "$dst"
done

printf '\nApply it with:  ~/.config/hypr/scripts/auto-monitor-profile.sh --force\n'
