#~/.config/hypr/hyprpaper.conf

splash = false
ipc = true

preload = /home/liam/Pictures/Wallpapers/dynamic/Lost-In-Dream-Sunset.mkv

wallpaper {
    monitor =
    path = /home/liam/Pictures/Wallpapers/dynamic/Lost-In-Dream-Sunset.mkv
    fit_mode = cover
}
