# ~/.config/hypr/hyprpaper.conf

splash = false
ipc = true

wallpaper {
    monitor =
    path = /home/liam/Pictures/wallpapers/band-music-rainbow-album-cover-hard-rock-wallpaper-preview.jpg
    fit_mode = cover
}
