-- Generated by nwg-displays on 2026-08-25 at 16:18:01. Do not edit manually.

hl.monitor({
    output = "DP-4",
    mode = "1280x1024@60.02",
    position = "0x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-3",
    mode = "2560x1080@60.0",
    position = "1024x0",
    scale = 1
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1080@60.0",
    position = "4240x0",
    scale = 1
})
