-- Generated by nwg-displays on 2026-07-15 at 15:39:39. Do not edit manually.

hl.monitor({
    output = "DP-1",
    mode = "1280x1024@60.02",
    position = "0x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "HDMI-A-1",
    mode = "2560x1080@60.0",
    position = "1050x0",
    scale = 1.0
})
