-- Generated by nwg-displays on 2026-07-15 at 09:26:21. Do not edit manually.

hl.monitor({
    output = "eDP-1",
    mode = "2256x1504@60.0",
    position = "0x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-5",
    mode = "1920x1080@60.0",
    position = "3336x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-7",
    mode = "1920x1080@60.0",
    position = "2256x0",
    scale = 1.0,
    transform = 1
})
hl.monitor({
    output = "DP-9",
    mode = "1920x1080@60.0",
    position = "5256x0",
    scale = 1.0
})
