-- Generated by nwg-displays on 2026-07-13 at 10:52:28. Do not edit manually.

hl.workspace_rule({
    workspace = "1",
    monitor = "DP-6",
    default = true
})
hl.workspace_rule({
    workspace = "2",
    monitor = "DP-6"
})
hl.workspace_rule({
    workspace = "3",
    monitor = "DP-6"
})
hl.workspace_rule({
    workspace = "4",
    monitor = "DP-6"
})
hl.workspace_rule({
    workspace = "5",
    monitor = "DP-6"
})
hl.workspace_rule({
    workspace = "6",
    monitor = "DP-10",
    default = true
})
hl.workspace_rule({
    workspace = "7",
    monitor = "DP-10"
})
hl.workspace_rule({
    workspace = "8",
    monitor = "DP-10"
})
hl.workspace_rule({
    workspace = "9",
    monitor = "DP-10"
})
hl.workspace_rule({
    workspace = "10",
    monitor = "DP-10"
})
hl.workspace_rule({
    workspace = "11",
    monitor = "DP-12",
    default = true
})
hl.workspace_rule({
    workspace = "12",
    monitor = "DP-12"
})
hl.workspace_rule({
    workspace = "13",
    monitor = "DP-12"
})
hl.workspace_rule({
    workspace = "14",
    monitor = "DP-12"
})
hl.workspace_rule({
    workspace = "15",
    monitor = "DP-12"
})
