# ~/.config/hypr/windows-rules.conf
# Hyprland window rules
# Keep this file focused on window behavior only.

############################
# Generic floating behavior
############################

windowrule {
    name = float-modal
    match:modal = true

    float = on
    center = on
}

windowrule {
    name = round-floating
    match:float = true

    rounding = 10
    border_size = 2
}

windowrule {
    name = dim-floating
    match:float = true

    dim_around = on
}

############################
# Fullscreen polish
############################

windowrule {
    name = fullscreen-border
    match:fullscreen = true

    border_color = rgb(89B4FA) rgb(CBA6F7)
}

############################
# App-specific rules
############################

# Brave opacity: active 1.0, inactive 0.95, fullscreen 1.0
windowrule {
    name = brave-opacity
    match:class = brave-browser

    opacity = 1.0 override 0.95 override 1.0 override
}

windowrule {
    name = obsidian-ws
    match:class = ^(obsidian|Obsidian)$

    workspace = 3 silent
}

windowrule {
    name = virt-manager-ws
    match:class = ^(virt-manager)$

    workspace = 6 silent
}

windowrule {
    name = spotify-ws
    match:class = ^(Spotify|spotify)$

    workspace = 9 silent
}

windowrule {
    name = brave-ws
    match:class = ^(brave-browser)$

    workspace = 2 silent
}