# ~/.config/hypr/windowrules.conf
# Hyprland window rules
# Keep this file focused on window behavior only.

############################
# Generic floating behavior
############################

windowrule {
    name = float-modal
    match:modal = true

    float = on
    center = on
}

windowrule {
    name = round-floating
    match:float = true

    rounding = 10
    border_size = 2
}

windowrule {
    name = dim-floating
    match:float = true

    dim_around = on
}

############################
# Fullscreen polish
############################

windowrule {
    name = fullscreen-border
    match:fullscreen = true

    border_color = rgb(89B4FA) rgb(CBA6F7)
}

############################
# Optional app-specific examples
# Uncomment and edit these later
############################

# Put Firefox on workspace 2
# windowrule = workspace 2, match:class firefox

# Float and center file picker windows
# windowrule = float on, center on, match:title .*Open File.*

# Slightly different opacity for one app
windowrule = opacity 1.0 override 0.95 override 1.0 override, match:class Brave-browser

# Give one app extra rounding
# windowrule = match:class kitty, rounding 12
windowrule = match:class ^(obsidian|Obsidian)$, workspace 3 silent
windowrule = match:class ^(virt-manager)$, workspace 6 silent
windowrule = match:class ^(Spotify|spotify)$, workspace 9 silent
windowrule = match:class ^(brave-browser)$, workspace 2 silent
