pragma Singleton
import Quickshell
import Quickshell.Io
import QtQuick

// Central palette, typography and metrics for the whole shell.
//
// The palette follows the desktop theme rather than being hardcoded: the theme
// generator (`theme set <slug>`) writes the active theme's semantic palette to
// themes/.active/theme.json, which is watched here, so switching the theme
// recolours the bar and its panels live. The hex literals below survive as
// fallbacks for when that file cannot be read; they are the colours the shell
// used before it was themed.
//
// `fs()` is the "Text Size" knob exposed by DisplayPanel: every font size and
// text-dependent dimension goes through it so that changing the scale rescales
// the bar and its panels as a whole.
Singleton {
  id: root

  // --- palette ---
  // Semantic keys, exposed through the names the rest of the shell already uses.
  readonly property color bg: col("background", "#2b2430")        // bar + panel background
  readonly property color bgDeep: col("backgroundAlt", "#1c1720") // deepest bg / text on accent
  readonly property color surface: col("surface", "#3a3240")      // rows, dividers, borders
  readonly property color accent: col("accent", "#8a6fae")        // active / focused / filled
  readonly property color text: col("foreground", "#d7d2db")      // primary text
  readonly property color textDim: col("muted", "#a89fb0")        // secondary text
  readonly property color textMuted: col("disabled", "#7d7686")   // disabled / muted
  readonly property color textFaint: col("overlay", "#5b5560")    // out-of-range
  readonly property color error: col("red", "#e08a8a")            // error text

  // Hyprland's own window border colours, so shell chrome can match the borders
  // the compositor draws. Same source, the theme's accent.
  readonly property color borderActive1: col("accent", "#8a6fae")
  readonly property color borderActive2: col("accent", "#8a6fae")
  readonly property int hyprRounding: num("rounding", 4)

  // --- theme source -----------------------------------------------------------
  // theme.json is generated by `theme-generate set` and carries the full
  // semantic palette (`colors.*`, `style.*`) as ready-to-use "#RRGGBB" hex.

  readonly property string themeFile: Quickshell.env("HOME") + "/.config/hypr/themes/.active/theme.json"

  property var themeData: ({})          // parsed theme.json
  readonly property var themeColors: root.themeData["colors"] || ({})
  readonly property var themeStyle: root.themeData["style"] || ({})

  // Semantic colour by key, falling back to the shell's original literal.
  function col(key, fallback) {
    const v = root.themeColors[key]
    return (typeof v === "string" && v.length > 0) ? v : fallback
  }

  // Same, for the theme's `style` block.
  function num(key, fallback) {
    const v = root.themeStyle[key]
    return typeof v === "number" ? v : fallback
  }

  FileView {
    id: themeFileView
    path: root.themeFile
    watchChanges: true
    printErrors: false

    onFileChanged: reload()
    onLoaded: {
      try {
        root.themeData = JSON.parse(themeFileView.text()) || ({})
      } catch (e) {
        console.warn("Theme: theme.json is not valid JSON:", e)
        root.themeData = ({})
      }
    }
    // Leave themeData empty so every colour falls back to its literal.
    onLoadFailed: root.themeData = ({})
  }

  // --- typography ---
  readonly property string glyphFamily: "JetBrainsMono Nerd Font"
  readonly property string uiFamily: "sans-serif"

  // --- radii ---
  // Scaled with the text so that pill shapes stay pills as rows grow.
  readonly property int radiusRow: fs(4)
  readonly property int radiusCell: fs(5)
  readonly property int radiusTrack: fs(10)

  // --- scaling ---
  // Persisted to disk; also mirrored to GTK apps via gsettings.
  property alias fontScale: stateData.fontScale

  readonly property var textScalePresets: [0.9, 1.0, 1.1, 1.25, 1.5]

  // Scale a design-time pixel value. Reads `fontScale`, so bindings that call
  // this re-evaluate when the scale changes.
  function fs(n) {
    return Math.round(n * root.fontScale)
  }

  // --- drawer / card tokens ---------------------------------------------------
  // Caelestia-style proportions for the dashboard drawer. Everything goes through
  // fs() so the Text Size control still scales the whole drawer.
  readonly property int gapXS: fs(4)
  readonly property int gapS: fs(8)
  readonly property int gapM: fs(12)
  readonly property int gapL: fs(16)
  readonly property int gapXL: fs(24)

  readonly property int radiusS: fs(12)
  readonly property int radiusM: fs(16)
  readonly property int radiusL: fs(20)
  readonly property int radiusXL: fs(26)

  readonly property int drawerPadding: fs(16)
  readonly property int navHeight: fs(60)
  readonly property int navIcon: fs(21)
  readonly property int navLabel: fs(13)
  readonly property int tabIndicator: fs(3)
  readonly property int tabIndicatorGap: fs(5)

  // Page intrinsic sizes. These are what the drawer animates between.
  readonly property int dashPageW: fs(720)
  // Tall enough for the full 6-week calendar grid (~250px) plus both rows.
  readonly property int dashPageH: fs(694)
  readonly property int mediaPageW: fs(900)
  readonly property int mediaPageH: fs(480)
  readonly property int perfPageW: fs(860)
  readonly property int perfPageH: fs(352)
  readonly property int weatherPageW: fs(840)
  // header(180) + gap + hourly(170) + gap + forecast(250)
  readonly property int weatherPageH: fs(624)
  readonly property int weatherHeaderH: fs(180)
  readonly property int hourlyCardH: fs(170)
  // 7 rows of 24 + 4 spacing, plus card title and padding.
  readonly property int forecastCardH: fs(250)

  // Card sizes
  readonly property int weatherCardW: fs(250)
  readonly property int weatherCardH: fs(170)
  readonly property int profileCardW: fs(300)
  readonly property int dateCardW: fs(120)
  readonly property int dateCardH: fs(200)
  // 6-week grid (~240) + card title (~22) + padding (32).
  readonly property int calendarCardH: fs(300)
  readonly property int mediaPreviewW: fs(230)
  readonly property int coverSize: fs(280)
  readonly property int mediaSideW: fs(290)
  readonly property int lyricsW: fs(290)
  readonly property int heroCardW: fs(260)
  readonly property int heroCardH: fs(210)
  readonly property int heroGauge: fs(92)
  // Five of these plus four gaps must fit perfPageW: 5*162 + 4*12 = 858.
  readonly property int smallCardW: fs(162)
  readonly property int smallCardH: fs(130)
  readonly property int hourCardW: fs(85)
  readonly property int hourCardH: fs(120)
  readonly property int avatarSize: fs(66)

  // --- keybindings menu tokens ------------------------------------------------
  // Every dimension and colour weight of the Super+K palette lives here; nothing
  // in KeybindsPanel.qml is hardcoded, so the whole look is tuned from this block.
  readonly property int menuWidth: fs(800)
  readonly property int menuMaxHeight: fs(500)
  readonly property int menuHeaderHeight: fs(34)
  readonly property int menuRowHeight: fs(50)
  readonly property int menuPadding: fs(24)      // generous side padding, as in the reference
  readonly property int menuFontBody: fs(12)
  readonly property int menuFontTitle: fs(14)
  readonly property int menuBorderWidth: fs(2)
  readonly property int menuRadius: fs(6)        // near-square, matching Hyprland's rounding
  readonly property int menuOuterMargin: fs(40)  // smallest gap to the screen edge
  // Shortcut column is measured from the longest visible shortcut, then clamped
  // here so the arrow never drifts between rows.
  readonly property int menuColumnMin: fs(160)
  readonly property int menuColumnMax: fs(260)
  readonly property real menuScrimOpacity: 0.50
  readonly property real menuSelectedAlpha: 0.08 // selected row bg: foreground @ 8%
  readonly property real menuBorderAlpha: 0.25   // selected row border

  // Shared easing for drawer resize and indicator movement.
  readonly property int animFast: 130

  // Metrics that must track the font scale so text does not clip.
  // 45px bar = ~33px inner widget area + ~6px padding above and below.
  readonly property int barHeight: fs(45)
  readonly property int barInner: fs(33)
  readonly property int panelMargin: fs(16)
  readonly property int sectionSpacing: fs(14)
  readonly property int itemSpacing: fs(8)

  // --- persistence ---
  FileView {
    id: stateFile
    path: Quickshell.statePath("shell-state.json")
    watchChanges: true
    printErrors: false

    onFileChanged: reload()
    onAdapterUpdated: writeAdapter()

    // First run: no file yet, so create it from the defaults.
    onLoadFailed: function (error) {
      if (error === FileViewError.FileNotFound)
        stateFile.writeAdapter()
    }

    JsonAdapter {
      id: stateData
      property real fontScale: 1.0
    }
  }

  // Mirror the shell font scale onto GTK apps. Fires on startup too, so the
  // persisted value is re-asserted after a reboot; the JSON file is the source
  // of truth, not the current gsettings value.
  onFontScaleChanged: root.applyGtkTextScale()

  function applyGtkTextScale() {
    const s = Number(root.fontScale)
    if (!isFinite(s) || s <= 0)
      return
    gtkScaleProc.command = ["gsettings", "set",
                            "org.gnome.desktop.interface",
                            "text-scaling-factor", s.toFixed(2)]
    gtkScaleProc.running = true
  }

  Process {
    id: gtkScaleProc
    stdout: StdioCollector {}
    stderr: StdioCollector { id: gtkScaleErr }
    onExited: function (code) {
      if (code !== 0)
        console.warn("Theme: gsettings text-scaling-factor failed:",
                     gtkScaleErr.text.trim())
    }
  }
}
